 
  (function () {
    "use strict";

      function init() {
          if (typeof gsap === "undefined" || typeof ScrollTrigger === "undefined") {
                setTimeout(init, 50);
                      return;
                          }

                              gsap.registerPlugin(ScrollTrigger);

                                  var section = document.querySelector("#hero-slider");
                                      var track = section.querySelector(".track");
                                          var slides = Array.from(section.querySelectorAll(".slide"));
                                              var dots = Array.from(section.querySelectorAll(".dot"));
                                                  var counterEl = section.querySelector(".counter-now");
                                                      var totalEl = section.querySelector(".counter-tot");
                                                          var fillEl = section.querySelector(".scroll-fill");

                                                              // Background hex per slide
                                                                  var bgColors = slides.map(function (s) { return s.dataset.bg; });
                                                                      var uiModes = slides.map(function (s) { return s.dataset.ui || "light"; });
                                                                          track.style.width = (slides.length * 100) + "vw";

                                                                              // Colour helpers
                                                                                  function hexToRgb(hex) {
                                                                                        var h = hex.replace("#", "");
                                                                                              if (h.length === 3) h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
                                                                                                    var n = parseInt(h, 16);
                                                                                                          return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
                                                                                                              }
                                                                                                                  function lerp(a, b, t) { return Math.round(a + (b - a) * t); }
                                                                                                                      function lerpColor(hexA, hexB, t) {
                                                                                                                            var a = hexToRgb(hexA), b = hexToRgb(hexB);
                                                                                                                                  return "rgb(" + lerp(a.r, b.r, t) + "," + lerp(a.g, b.g, t) + "," + lerp(a.b, b.b, t) + ")";
                                                                                                                                      }

                                                                                                                                          // Set initial state
                                                                                                                                              section.style.backgroundColor = bgColors[0];
                                                                                                                                                  var activeIdx = 0;
                                                                                                                                                      if (totalEl) totalEl.textContent = ("0" + slides.length).slice(-2);
                                                                                                                                                          activateSlide(0);

                                                                                                                                                              function activateSlide(idx) {
                                                                                                                                                                    activeIdx = idx;
                                                                                                                                                                          slides.forEach(function (s, i) { s.classList.toggle("active", i === idx); });
                                                                                                                                                                                dots.forEach(function (d, i) { d.classList.toggle("active", i === idx); });
                                                                                                                                                                                      if (counterEl) counterEl.textContent = ("0" + (idx + 1)).slice(-2);
                                                                                                                                                                                            section.classList.toggle("dark-ui", uiModes[idx] === "dark");
                                                                                                                                                                                                }

                                                                                                                                                                                                    // GSAP: move track left as user scrolls
                                                                                                                                                                                                        gsap.to(track, {
                                                                                                                                                                                                              x: function () { return -(slides.length - 1) * window.innerWidth; },
                                                                                                                                                                                                                    ease: "none",
                                                                                                                                                                                                                          scrollTrigger: {
                                                                                                                                                                                                                                  trigger: section,
                                                                                                                                                                                                                                          start: "top top",
                                                                                                                                                                                                                                                  end: function () { return "+=" + (slides.length - 1) * window.innerHeight; },
                                                                                                                                                                                                                                                          pin: true,
                                                                                                                                                                                                                                                                  scrub: 0.3,
                                                                                                                                                                                                                                                                          invalidateOnRefresh: true,
                                                                                                                                                                                                                                                                                  snap: {
                                                                                                                                                                                                                                                                                            snapTo: 1 / (slides.length - 1),
                                                                                                                                                                                                                                                                                                      duration: 1,
                                                                                                                                                                                                                                                                                                                ease: "expo.out",
                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                onUpdate: function (self) {
                                                                                                                                                                                                                                                                                                                                          // lerp bg colour
                                                                                                                                                                                                                                                                                                                                                    var raw = self.progress * (slides.length - 1);
                                                                                                                                                                                                                                                                                                                                                              var from = Math.min(Math.floor(raw), slides.length - 2);
                                                                                                                                                                                                                                                                                                                                                                        var t = raw - from;
                                                                                                                                                                                                                                                                                                                                                                                  section.style.backgroundColor = lerpColor(bgColors[from], bgColors[from + 1], t);

                                                                                                                                                                                                                                                                                                                                                                                            // progress bar
                                                                                                                                                                                                                                                                                                                                                                                                      if (fillEl) fillEl.style.width = (self.progress * 100) + "%";

                                                                                                                                                                                                                                                                                                                                                                                                                // active slide
                                                                                                                                                                                                                                                                                                                                                                                                                          var snap = Math.round(raw);
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (snap !== activeIdx) activateSlide(snap);
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (document.readyState === "loading") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.addEventListener("DOMContentLoaded", init);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    init();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         /* ===== 3D TILT CARDS (collections) ===== */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           document.querySelectorAll('.col-card').forEach(card => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               card.addEventListener('mousemove', e => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const r = card.getBoundingClientRect();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const dx = ((e.clientX - r.left) / r.width - 0.5) * 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const dy = ((e.clientY - r.top) / r.height - 0.5) * 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       card.style.transform = `perspective(1000px) rotateX(${-dy * 8}deg) rotateY(${dx * 8}deg) translateY(-10px) scale(1.02)`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               card.addEventListener('mouseleave', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     card.style.transform = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             /* ===== COUNT-UP ON SCROLL ===== */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               function startCountUp(el) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const target = parseInt(el.dataset.target);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const duration = 1500, start = performance.now();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           (function update(now) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const p = Math.min((now - start) / duration, 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const ease = 1 - Math.pow(1 - p, 3);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             el.textContent = p < 1 ? Math.floor(ease * target) : target;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (p < 1) requestAnimationFrame(update);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       })(start);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           new IntersectionObserver(entries => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               entries.forEach(e => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (e.isIntersecting) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             e.target.querySelectorAll('.count[data-target]').forEach(startCountUp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }, { threshold: 0.5 }).observe(document.getElementById('nutrition'));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           /* ===== GSAP SCROLL REVEALS ===== */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             gsap.registerPlugin(ScrollTrigger);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               document.querySelectorAll('.reveal').forEach(el => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const delay = parseFloat(el.dataset.delay || 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       gsap.to(el, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             opacity: 1, y: 0, duration: 0.9, delay, ease: 'power3.out',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   scrollTrigger: { trigger: el, start: 'top 88%', toggleActions: 'play none none none' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           gsap.from('#pills-stage .ing-pill', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               opacity: 0, y: 30, scale: 0.8, stagger: 0.1, ease: 'back.out(1.6)', duration: 0.7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   scrollTrigger: { trigger: '#pills-stage', start: 'top 80%' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       function applyEmojiHoverColors() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         document.querySelectorAll('.ing-list li').forEach(li => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const text = li.textContent.trim().toLowerCase();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 let color = '100, 160, 200'; // fallback blue

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (text.includes('blueberry'))     color = '100, 80, 180';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (text.includes('strawberry'))    color = '220, 60, 80';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (text.includes('mango'))         color = '255, 150, 40';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (text.includes('vanilla'))       color = '255, 200, 80';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (text.includes('natural'))       color = '100, 180, 230';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (text.includes('raspberry'))     color = '200, 80, 120';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (text.includes('mixed berries')) color = '140, 80, 180';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (text.includes('coffee'))        color = '120, 80, 50';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (text.includes('chocolate'))     color = '100, 60, 40';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (text.includes('caramel'))       color = '230, 170, 80';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (text.includes('cookie'))        color = '200, 140, 80';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (text.includes('coconut'))       color = '130, 200, 160';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (text.includes('almond'))        color = '200, 160, 100';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (text.includes('lactose'))       color = '180, 220, 200';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (text.includes('smoothie'))      color = '220, 80, 100';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (text.includes('zero sugar'))    color = '100, 200, 160';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (text.includes('kulfi'))    color = '128, 0, 0';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             li.style.setProperty('--pill-color', color);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (document.readyState === "loading") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 document.addEventListener("DOMContentLoaded", applyEmojiHoverColors);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   applyEmojiHoverColors();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }